image: ubuntu:16.04

before_script:
    - apt update && apt install -y sudo git  module-init-tools  passwd 

stages:
  - build
  - build-master
  - build-worker

install:
  tags:
    - shell-runner
  stage: build
  script:
    - ./install.sh

install-master:
  tags:
    - shell-runner
  stage: build-master
  script:
    - ./install.sh --master


install-worker:
  tags:
    - shell-runner
  stage: build-worker
  script:
    - ./install.sh --token SWMTKN-1-2f98skv0z2vdhnyw9liwbqtgocts6comdr81o6e3u6kd9olbrc-48zv9ho4f3poid4d34767nucj 192.168.4.101:2377

